### PR TITLE
Silences logger by default

### LINKED ISSUE #122: zOS's logging garbles Mocha's output
The info logs from zOS make the test log output hard to read, and add no information (except possibly on failing tests).

A workaround to this is to overwrite the `Logger` functions in the test file:
```
const Logger = require('zos-lib/lib/utils/Logger').default;
Logger.prototype.info = () => {};
Logger.prototype.error = () => {};
```

We could mute `Logger` when testing, though this info could be useful when debugging a failing test. Suggestions are welcome.

Sample output: 

image

### PR DESCRIPTION
**Pull request by spalladino**
Logger is now silent by default, and must be activated (either
globally or per instance) in order to actually log. Added verbose
flag to control whether to output prefixes or not.

Closes #122

### CODE REVIEW

**Comment by nventuro** [comment]
Does cli have a way of turning on the logs?

Also, this closes #122

File: src/utils/Logger.js [hunk 1]
```diff
@@ -1,19 +1,44 @@
...
+
+  static silent(value) {
+    defaults.silent = value;
+  }
+
+  static verbose(value) {
+    defaults.verbose = value;
   }
-}
+}
```
Comment (facuspagnuolo) [inline src/utils/Logger.js]: I'd simply move the static methods above the constructor since these are the entry-points of this object
