### PR TITLE
Fix decodeLogs when logs include events from other contracts

### LINKED ISSUE #72: decodeLogs throws "cannot find inputs of undefined"
It appears that decodeLogs.js is not properly dealing with the situation exposed below.
It attempts to read an object that does not exist.

CLI command executed:
```
[AppManager] 
Setting implementation of Basil in contract directory...
[AppManager]  Implementation set: 0x77092acc78ed6cc2439fdc6bdf07d51271d76028
[AppManager] 
Setting stdlib [object Object]...
[PackageFilesInterface] Successfully written package.zos.development.json
zos create-proxy Basil --init --params 0x65a59bb097403551a3bb6cb2bd987389f2872d40 --network development
Using network 'development'.

[AppManager] 
Creating Basil proxy: initialize, 0x65a59bb097403551a3bb6cb2bd987389f2872d40...
[AppManager]  TX receipt received: 0xb6049b7a15aad01486d59d5b53a7376dd80c62e810b5aeff547f80ef74678d64
```

Error thrown:
```
TypeError: Cannot read property 'inputs' of undefined
    at new SolidityEvent (/home/ajs/zos/lib/node_modules/web3/lib/web3/event.js:35:25)
    at logs.map.log (/home/ajs/zos/lib/lib/decodeLogs.js:7:19)
    at Array.map (<anonymous>)
    at decodeLogs (/home/ajs/zos/lib/lib/decodeLogs.js:4:15)
    at AppManagerWrapper.createProxy (/home/ajs/zos/cli/src/models/AppManager.js:98:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

`console.log(JSON.stringify(log, null, 2))` in decodeLogs.js, after line 4:
```
{
  "logIndex": 1,
  "transactionIndex": 0,
  "transactionHash": "0xb6049b7a15aad01486d59d5b53a7376dd80c62e810b5aeff547f80ef74678d64",
  "blockHash": "0x053e80721d45f5eb17e6b2382518e91ed7c0e13cf574652831e440775599d233",
  "blockNumber": 94,
  "address": "0x9c45ea32ca605d59bc82a966c73be2b29647fb53",
  "data": "0x0",
  "topics": [
    "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b",
    "0x00000000000000000000000077092acc78ed6cc2439fdc6bdf07d51271d76028"
  ],
  "type": "mined"
}
```

`console.log(JSON.stringify(contract.events, null, 2))`
```
{
  "0x00fffc2da0b561cae30d9826d37709e9421c4725faebc226cbbb7ef5fc5e7349": {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "proxy",
        "type": "address"
      }
    ],
    "name": "ProxyCreated",
    "type": "event"
  }
}
```

### PR DESCRIPTION
**Pull request by frangio**
I think this fixes #72.

The problem was that a transaction can include events from other contracts, thus sometimes `contract.events[log.topics[0]]` was evaluating to `undefined`.

### CODE REVIEW

File: lib/decodeLogs.js [hunk 1]
```diff
@@ -1,10 +1,17 @@
...
+  
+  for (const log of logs) {
+    const eventName = log.topics[0];
+    if (eventName in contract.events) {
+      const eventType = new SolidityEvent(null, contract.events[eventName], '0x0');
+      decodedLogs.push(eventType.decode(log));
+    }
+  }
+        
+  return decodedLogs;
```
Comment (facuspagnuolo) [inline lib/decodeLogs.js]: What about doing the ES6 way? it could be sth like:
```js
return logs.reduce((decodedLogs, log) => {
   const eventName = log.topics[0]
   if(!(eventName in contract.events)) return decodedLogs;
   const eventType = new SolidityEvent(null, contract.events[eventName], '0x0');
   return decodedLogs.concat(eventType.decode(log));
}, [])
```

Comment (frangio) [reply lib/decodeLogs.js]: I would keep the `for` loop, I find it much easier to read.

Comment (ajsantander) [reply lib/decodeLogs.js]: Good. This basically adds a check for the topic existing in the contract's events before just trying to read it.
Be aware that CLI calls this with:
```
    const logs = decodeLogs([receipt.logs[1]], UpgradeabilityProxyFactory);
```
i.e. with only the 2nd log.
We would have to change usage of decodeLogs in the CLI and elsewhere to:
```
    const logs = decodeLogs(receipt.logs, UpgradeabilityProxyFactory);
```

**Comment by ajsantander** [comment]
Good. This basically adds a check for the topic existing in the contract's events before just trying to read it.

Be aware that CLI tests fail with this change, because it calls decodeLogs with:
```
    const logs = decodeLogs([receipt.logs[1]], UpgradeabilityProxyFactory);
```
i.e. with only the 2nd log.
We would have to change usage of decodeLogs in the CLI and elsewhere to:
```
    const logs = decodeLogs(receipt.logs, UpgradeabilityProxyFactory);
```

**Comment by ajsantander** [comment]
PR in zos-cli made:
https://github.com/zeppelinos/zos-cli/pull/48
